### ISSUE TITLE
UI crashes when showing multicall args with invalid JSON

### ISSUE THREAD

**Issue by lennczar** [near-multicall/ui#112]
**Describe the bug**
The UI will crash if there is an invalid JSON in a custom card and the user opens multicall args on the export page.

**To Reproduce**
1. Drag in a custom card
2. Input an invalid JSON in the arguments
3. Go to export page
4. Unfold the multicall args section
5. UI crashes

**Expected behavior**
Good question, i guess show a broken multicall args?

**Screenshots**
![image](https://user-images.githubusercontent.com/42617542/170831337-c3069e87-da80-48b4-8a50-d48b5cc130c8.png)
Invalid card like this will make it crash

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox

**Comment by mohamedalichelbi** [comment]
This is caused by the `base64.encode()` throwing when it gets an invalid input value, like `undefined` in our case.
Just wanna point out that `toBase64()` and `toJSON()` has unexpected behavior because of this. For example, when cloning a card with invalid JSON args (like `{"potato": }`), you get a new card with `{}` (default JSON args). I think this is smth to keep in mind when working on a new way to validate args in general (for example: allow cloning invalid JSON args)
