### ISSUE TITLE
[DAO tab] MENU is undefined

### ISSUE THREAD

**Issue by mohamedalichelbi** [near-multicall/ui#113]
**Describe the bug**
Following error appears on DAO tab
<img width="960" alt="image" src="https://user-images.githubusercontent.com/28174037/170892776-e409b1be-ff34-45a0-83b7-f831b8b501d7.png">

**To Reproduce**
1. Go to https://multicall.app/#/dao
2. open browser dev tools
3. choose any DAO in the DAO selector

**Expected behavior**
Make sure MENU is defined before 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser: firefox
 - Version: latest

**Comment by lennczar** [comment]
# Reason
## Scenario 1 (*all good*): User comes from APP page to DAO page
In this case the `MENU` has already been mounted, so it's defined. The Dao selector will now update the Dao address, which includes changing value on cards or other stuff in the `MENU`. This works as intended.

## Scenario 2 (*error occurs*): User starts off on the DAO page or refreshed
Now `MENU` is not mounted, but the same code from before will try to update the values in the `MENU` and fails (causing the error in question). This is not really a problem since the `MENU` will load the address from the Dao selector whenever it's mounted.

## Conclusion
The error is not at all critical and can simply be caught and dismissed.
